feat: 공모글 작성 API 연결
woowacourse-teams/2024-chongdae-market pull request #162
Opened 2024-08-04 13:53 UTC by songpink

## 📌 관련 이슈
close #146 
## ✨ 작업 내용
- 공모글 작성 API 연결했습니다. 올바른 입력값을 입력한 후 "공동구매 시작하기" 버튼을 클릭하면 서버로 공모글이 보내집니다.
- 필수 작성 항목을 모두 입력하지 않으면 버튼이 비활성화 상태이며, 모두 입력해야 활성화 됩니다.
- 총원, 총가격, 낱개가격을 잘못 입력할 시 해당 항목을 제대로 입력하라는 토스트를 띄웁니다. 
    - 총원은 2~10000의 정수가 아니거나 빈칸이면 토스트를 띄웁니다.
    - 총 가격은 0이상의 정수가 아니거나 빈칸이면 토스트를 띄웁니다.
    - 낱개 가격은 0이상의 정수가 아니면 토스트를 띄우고, 빈칸이라면 null을 보냅니다.
- 앱 아이콘 변경했습니다. (토스트 아이콘이 앱 아이콘을 따라가서 바꿈)
- 앱 이름 변경했습니다. chongdae -> 총대마켓 (아이콘 바꾸는 김에 바꿈)
- 예상 엔빵 가격과 할인율을 계산해서 보여줍니다.
    - 총원, 총가격, 낱개가격이 올바른 값이 아닐 경우 invisible상태로 바꿔서 보이지 않습니다.
    - 예상 엔빵 가격은 0 초과 Int일 경우에만 보여줍니다.
    - 할인율은 0 이상의 Float일 때에만 보여지고, 소수점 첫째자리까지 반올림해서 보여줍니다.
- 총원 양옆의 +, - 버튼으로 총원을 조절할 수 있습니다.

[146-시연영상1.webm](https://github.com/user-attachments/assets/0d4c8ed4-62e4-44eb-afbe-981f07a90b04)

[146-시연영상2.webm](https://github.com/user-attachments/assets/f0d23ae9-5ed2-486c-8e97-259edf5ac94d)

[146-시연영상3-총원조정.webm](https://github.com/user-attachments/assets/5ae78262-0b69-4450-b27d-33d4fbd8b669)

## 📚 기타
- ui state를 쓰면 훨씬 코드가 깔끔해질 것 같은데, 시간이 되면 리팩토링 하려고 합니다.. ㅠ

2024-08-04 16:52 UTC, Namyunsuk requested changes
구현 하시면서  까다로운 부분이 많으셨을 텐데 정말 고생하셨습니다~~😃
리뷰 몇개(?) 남겼어요!!ㅋㅋ

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +fun Button.setSubmitButtonEnabled(buttonEnabled: Boolean) {
이 부분이 버튼 활성화 비활성화에 따라 배경을 다르게 주는 것으로 보이는데용
selector를 사용하면 해당 BindingAdapter를 사용하지 않아도 될 것 같아요~!

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +fun TextView.setSplitPriceVisibility(splitPrice: Int) {
` if (splitPrice >= 0)`이 상태를 뷰모델이 가지고 있으면 기존에 만들어 두었던 bindingAdapter를 활용할 수 도 있을 것 같아요!

```
@BindingAdapter("isVisible")
fun View.setIsVisible(isVisible: Boolean) {
    visibility = if (isVisible) View.VISIBLE else View.GONE
}
```

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +    val textVisibility = if (discountRate >= 0) View.VISIBLE else View.INVISIBLE
이 부분도 위 리뷰와 같이 상태를 뷰모델내부에서 계산하여 가지고 boolean만 넘기는 방식으로 기존 bindingAdapter를 활용할 수 있을 것 같아요!

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +    val formattedNumber = context.getString(R.string.all_money_amount_text).format(number)
바인딩어댑터를 활용하기 보다는 xml내에서 처리할 수 도 있을 것 같아요!

예를 들면 아래와 같이요!
`android:text="@{@string/all_money_amount_text(number)}"`

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +    val formattedRate = context.getString(R.string.write_discount_rate_value).format(number)
위 리뷰와 동일하게 xml내에서 처리할 수 있을 것 같아요~!

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteUiState.kt
> +data class OfferingWriteUiState(
pr메시지에 남겨두신것 처럼 나중에 적용하기 위해 생성하신건가용?
아 그리고 UiState인데 상태를 가지고 있지 않아보여요!

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
> +    val totalCount: MutableLiveData<String> = MutableLiveData("2")
기본 값이 2인 이유가 있을까요?? 제가 세부 조건들을 놓친 부분이 있어서 모르는 부분일 수 도 있을 것 같아서용 :)

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/res/layout/fragment_offering_write.xml
>                  android:id="@+id/img_minus_total_personnel"
네이밍컨벤션에 따르면 `tv_xxx`이렇게 수정되어야 할 것 같아요~

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/res/layout/fragment_offering_write.xml
>                  android:id="@+id/img_plus_total_personnel"
위 리뷰와 동일합니다! (네이밍 컨벤션)

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/res/layout/fragment_offering_write.xml
>                  android:id="@+id/img_minus_total_personnel"
아 혹시 그리고 -, +버튼을 텍스트뷰로 구현하신 것 같은데 이미지뷰나 버튼으로 구현하지 않은 이유가 있을까요..?

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/res/layout/fragment_offering_write.xml
>                  android:textStyle="bold"
font적용하면 좋을 것 같아요!

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
> +        val totalPriceInt = totalPrice.value?.toIntOrNull() ?: ERROR_INTEGER_FORMAT
변수들의 이름 뒤에 Int를 따로 명시하지 않아도 될 것 같아요. `toIntOrNull`로 충분히 정수여야 함을 보여주는 것 같고 혹시 나중에 자료형이 변경된다면 모든 변수의 네이밍을 변경하는 일이 생길 것 같아용

2024-08-04 16:52 UTC, Namyunsuk commented on android/app/src/main/res/layout/fragment_offering_write.xml
>                  android:layout_width="wrap_content"
글 작성 버튼인 것 같은데용, id를 사용할 일이 없어도 명시해 준다면 추후에 사용할 때나 코드를 읽을 때 가독성이 높아질 것 같아용!

2024-08-05 03:36 UTC, songpink commented on android/app/src/main/java/com/zzang/chongdae/data/remote/source/OfferingWriteDataSource.kt
> +interface OfferingWriteDataSource {
아! OfferingsDataSource에 하는 게 맞네요! API 연결에 익숙치 않은 이슈입니당.. 수정했어요!

2024-08-05 04:10 UTC, songpink commented on android/app/src/main/java/com/zzang/chongdae/data/remote/source/impl/OfferingWriteDataSourceImpl.kt
> +//                throw IllegalStateException()
디버깅용으로 썼던 코드인데 실수로 지우지 않았네요.. ㅎㅎ.. 삭제했습니다!

2024-08-05 04:16 UTC, songpink commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteUiState.kt
> +data class OfferingWriteUiState(
처음에 적용하려고 하다가 안해서 남아있네용.. 그리고 디폴트값도 추가하도록 할게요!

2024-08-05 05:34 UTC, chaehyuns reviewed
알송 코드 확인했어요!!
수고 정말 정말 많았서요!!
전체적으로 객체로 뺄 부분과 사소한 부분 남겨놓았습니다! 그리고 pr 자세하게 남겨주어서 감사함동

2024-08-05 05:34 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/data/repository/remote/OfferingWriteRepositoryImpl.kt
> +    override suspend fun saveOffering(
ui model을 사용하면 더 쉽게 전달할 수 있을 것 같아요!

2024-08-05 05:34 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/data/repository/remote/OfferingWriteRepositoryImpl.kt
> +    override suspend fun saveOffering(
(+ mapper)

2024-08-05 05:34 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +    val textVisibility = if (discountRate >= 0) View.VISIBLE else View.INVISIBLE
추가적으로 저희 binding adapter가 너무 중구난방으로 쓰이는 거 같아서 같이 정리하는 시간을 가졌으면 해요!!

2024-08-05 05:34 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteFragment.kt
> +    private fun observeInvalidInputEvent() {
중복적으로 사용되는 toast 들을 함수로 묶어보는 것은 어떤가요?

2024-08-05 05:34 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
> +    private fun updateDiscountRate() {
객체를 사용해서 계산하고 검증을 시키는 건 어떤가요!! viewmodel의 역할이 너무 큰것 같아요~~~

2024-08-05 05:34 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
> +        // 낱개 가격이 빈 문자열이면
이런 부분도 주석보다는 객체로 빼서 함수를 사용하는 식으로 나타내면 가독성이 더 좋을 거 같아요!

2024-08-05 05:36 UTC, songpink commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +fun Button.setSubmitButtonEnabled(buttonEnabled: Boolean) {
오 예전에 서기랑 페어했을 때 썼던 것 같은데 까먹었었네요.. ㅋㅋㅋ.. 수정했어요!

2024-08-05 05:52 UTC, songpink commented on android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
> +fun TextView.setSplitPriceVisibility(splitPrice: Int) {
앗 저번에 알려주신건데 벌써 까먹다니.. ㅠㅠ 수정했습니다!!

2024-08-05 06:08 UTC, songpink commented on android/app/src/main/res/layout/fragment_offering_write.xml
>                  android:id="@+id/img_minus_total_personnel"
어이구 버튼에는 텍스트가 안들어간다는 순간적인 착각을 했었네요.. 버튼으로 수정했습니당!

2024-08-05 06:37 UTC, songpink commented on android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
> +    private fun updateDiscountRate() {
인정합니다 레벨1때 연습했던 내용들인데 시간이 지나니 까먹는.. ㅠ

2024-08-05 08:58 UTC, songpink commented
서기 리뷰 반영하니까 바인딩 어댑터 싹다 없앨 수 있었네용.. ^^ 그리고 채채 리뷰대로 도메인 객체 분리하니까 코드 훨씬 깔끔해졌어요 고마워요~

2024-08-05 09:57 UTC, Namyunsuk approved these changes

2024-08-05 10:25 UTC, chaehyuns approved these changes
리뷰 반영하느라 수고했어요 알송! 지금 남긴 리뷰는 내일 이후에 찬찬히 반영해도 좋아요~

2024-08-05 10:25 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/data/remote/source/impl/OfferingsDataSourceImpl.kt
> +                response.body() ?: error("에러 발생: null")
Result<Unit>이기 때문에 null 일때 예외처리를 할 필요가 없는 거 같아요!

2024-08-05 10:25 UTC, chaehyuns commented on android/app/src/main/java/com/zzang/chongdae/data/repository/remote/OfferingsRepositoryImpl.kt
> +                OfferingWriteRequest(
mapper을 사용하면 코드를 관리하기 더 쉬울 거 같아요! 담에 다시 리팩토링 고고요

2024-08-05 10:27 UTC, Namyunsuk approved these changes
고생하셨습니당~ 나중에 api추가로 붙이실 때 수정하시면 될 것 같아서 어프루브 하겠습니당!

2024-08-05 10:27 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/domain/model/Count.kt
> +        if (number == 2) return Count(number)
상수화 해주면 좋을 것 같아용~

2024-08-05 10:27 UTC, Namyunsuk commented on android/app/src/main/java/com/zzang/chongdae/domain/model/Count.kt
> +    fun increase(): Count {
이거 operator사용해보는 것도 고려해보면 좋을 것 같아요!

2024-08-05 10:49 UTC, merged