feat: 공모 참여자 목록 조회 API 구현
woowacourse-teams/2024-chongdae-market pull request #225
Opened 2024-08-07 09:23 UTC by fromitive

## 📌 관련 이슈
close #219 
## ✨ 작업 내용
- 공모 참여자 목록 조회 API 구현
## 📚 기타

2024-08-07 10:02 UTC, masonkimseoul requested changes
고생하셨습니다! 코멘트 일부분 확인해주세요.

2024-08-07 10:02 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/global/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorMessage> handle(MissingServletRequestParameterException e) {
놓친 부분 알려줘서 감사합니다~

2024-08-07 10:02 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offeringmember/exception/OfferingMemberErrorCode.java
> +    PARTICIPANT_NOT_FOUND(BAD_REQUEST,"참여하지 않은 공모입니다.");
사소하지만,, 띄어쓰기 부탁드립니다!

2024-08-07 10:02 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +    }
나중에 Proposer와 Participant를 도메인으로 분리해보죠! 이 부분은 이번 단계엔 수정하시지 않아도 좋을 것 같습니다.

2024-08-07 10:13 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/exception/OfferingMemberErrorCode.java
> +    PARTICIPANT_NOT_FOUND(BAD_REQUEST,"참여하지 않은 공모입니다.");
띄어쓰기 적용하겠습니다~

2024-08-07 10:20 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +        List<ParticipantResponseItem> participants = members.getParticipants().stream()
추가로, participants 대신 response와 관련된 이름은 어떨까요? `responseItems`처럼요! 참여자 관련 변수라기보다는 응답 관련 변수라는 생각입니다.

2024-08-07 10:31 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +                .filter(OfferingMemberEntity::isProposer)
그러고보니, 여기도 도메인 로직이 있네요,,

2024-08-07 10:34 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +    }
위 코드를 개선할 수 있는 방안에 대해 언급드릴게요! 두 방법 중 선택해 진행하면 좋을 것 같습니다 :)

### 방안1
stream은 아래와 같이 `noneMatch()`라는 메서드를 제공합니다! filter 대신 사용하면 좋을 것 같아요~

```java
private void validateIsParticipants(MemberEntity member, List<OfferingMemberEntity> offeringMembers) {
    if (offeringMembers.stream()
            .noneMatch(offeringMember -> offeringMember.getMember().equals(member))) {
        throw new MarketException(/*어쩌구*/);
    }
}
```

### 방안2
service에 해당 메서드를 이동시킨다는 가정 하에, 아래 방법으로 DB를 찔러 검증해볼 수도 있겠네요~
```java
offeringMemberRepository.existsByOfferingAndMember(offering, member)
```

2024-08-08 01:16 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ProposerResponseItem.java
> +    public ProposerResponseItem(OfferingMemberEntity member) {
MemberEntity로 변경 완료했어요~

2024-08-08 01:35 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +    }
적용 완료했어요~~ 

https://github.com/woowacourse-teams/2024-chongdae-market/pull/225/commits/205e9fa0bc78779de691f616f0a7c15bb98107c4

2024-08-08 01:35 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +    }
적용 완료 했어요~~

[refactor: 참여 검증로직을 서비스로 이동](https://github.com/woowacourse-teams/2024-chongdae-market/pull/225/commits/205e9fa0bc78779de691f616f0a7c15bb98107c4)

2024-08-08 01:36 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +        List<ParticipantResponseItem> participants = members.getParticipants().stream()
적용 완료요~ 

[refactor: 참여 검증로직을 서비스로 이동](https://github.com/woowacourse-teams/2024-chongdae-market/pull/225/commits/205e9fa0bc78779de691f616f0a7c15bb98107c4)

2024-08-08 01:36 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +                .filter(offeringMemberEntity -> !offeringMemberEntity.isProposer())
너무 좋은 생각에요 😄 

[refactor: isParticipant를 구현하여 가독성 개선](https://github.com/woowacourse-teams/2024-chongdae-market/pull/225/commits/51e4d85534459b2b115cb4918df7000380fe19ff)

2024-08-08 01:37 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +                .orElseThrow(() -> new MarketException(OfferingMemberErrorCode.PARTICIPANT_NOT_FOUND));
총대를 찾을 수 없는 예외를 하나 추가했습니다~~

[refactor: 총대를 찾을 수 없는 상황의 예외 추가](https://github.com/woowacourse-teams/2024-chongdae-market/pull/225/commits/ee236c22f734aa7b64d1ac89d17ec5225e295508)

2024-08-08 01:37 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
> +    }
확실히 맴버는 맴버끼리 받으면 좋다고 생각해요 동의합니다~ 

[refactor: MemberEntity를 받도록 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/225/commits/635e25bed8e77b1b979d996dcecf4da918375100)

2024-08-08 01:39 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +    }
다음 스프린트로.. 변경합시다 이번에 전체 회의로 지금까지 짠 코드 설명하고 리펙터링 진행해야 할 것 같아요 다들 열심히 고생해주고 계시고 있으나 엔트로피가 계속 늘어나네요.. 

@ChooSeoyeon  @helenason

2024-08-08 01:40 UTC, fromitive commented
안녕하세요 리뷰 반영 완료하였고, 코멘트에 답글 달았습니다~ 😄 

혹시 또다른 의견이나 개선해야 할 점 있으시면 말씀해주세요~

다들 고생 많으십니다..!!! 화이팅!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2024-08-08 02:04 UTC, helenason commented
포케의 바쁨 이슈로 추가 리뷰하고 싶은 부분 직접 반영하였습니다.
확인해보시고 코멘트 남겨주세요~

1. 사용하지 않는 isSameMember 메서드를 제거하였습니다.
2. 참여자임을 검증하는 로직을 가장 상단으로 위치시켰습니다.
3. stream의 map을 사용하지 않고 구현할 수 있는 방법을 적용하였습니다.
    ```java
    public MemberEntity getProposer() {
        return offeringMembers.stream()
                .filter(OfferingMemberEntity::isProposer)
                .findFirst()
                .orElseThrow(() -> new MarketException(OfferingMemberErrorCode.PROPOSER_NOT_FOUND))
                .getMember();
    }
    ```

2024-08-08 02:06 UTC, helenason approved these changes
lgtm
고생 많았어 포케~

2024-08-08 02:08 UTC, fromitive commented
> 포케의 바쁨 이슈로 추가 리뷰하고 싶은 부분 직접 반영하였습니다.
> 
> 확인해보시고 코멘트 남겨주세요~
> 
> 
> 
> 1. 사용하지 않는 isSameMember 메서드를 제거하였습니다.
> 
> 2. 참여자임을 검증하는 로직을 가장 상단으로 위치시켰습니다.
> 
> 3. stream의 map을 사용하지 않고 구현할 수 있는 방법을 적용하였습니다.
> 
>     ```java
> 
>     public MemberEntity getProposer() {
> 
>         return offeringMembers.stream()
> 
>                 .filter(OfferingMemberEntity::isProposer)
> 
>                 .findFirst()
> 
>                 .orElseThrow(() -> new MarketException(OfferingMemberErrorCode.PROPOSER_NOT_FOUND))
> 
>                 .getMember();
> 
>     }
> 
>     ```

놓친부분 알려줘서 고마워요 😄

2024-08-08 02:16 UTC, masonkimseoul approved these changes
고생 많았습니다 ^_^

2024-08-08 02:17 UTC, merged