feat: 공모 참여 취소 기능 구현
woowacourse-teams/2024-chongdae-market pull request #318
Opened 2024-08-13 12:09 UTC by fromitive

## 📌 관련 이슈
close #314 
## ✨ 작업 내용
- 공모 참여 취소 기능 구현했습니다
## 📚 기타
리뷰 받고 싶은 부분은 코드에 코멘트 달겠습니다 😄

2024-08-13 12:10 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/domain/CommentRoomStatus.java
> +    }
공모가 진행중일 때 참여 취소가 불가능한게 맞나요?

2024-08-13 12:13 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
> +        return ResponseEntity.accepted().build();
delete메서드가 최초다 보니, delete를 반영했다는 의미로 Accepted를 반환했는데, Ok 가 좀 더 자연스러웠을까요?

2024-08-13 12:15 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/exception/OfferingMemberErrorCode.java
> +    CANNOT_CANCEL_IN_PROGRESS(BAD_REQUEST, "진행중인 공모는 참여를 취소할 수 없습니다.");
참여한 공모를 취소할 때 예외상황을 위와같이 정의했는데 좀 더 고려해야 할 예외 케이스가 있을까요?

2024-08-13 12:15 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +    private void validateCancel(OfferingMemberEntity offeringMember) {
취소를 검증하는 로직을 서비스 계층에 드러냈는데 읽기에 자연스러운지 궁금합니다 😄

2024-08-13 12:19 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +        CommentRoomStatus roomStatus = offering.getRoomStatus();
매개변수를 offeringMember로 받지만, 검증하기 위해선 `roomStatus`를 알아야하고 이를 `OfferingEntity`를 꺼내서 확인 할 수 밖에 없었는데요, `OfferingMemberEntity`에 물어보도록 변경하는게 좀 더 자연스러을까요?

혹은 `offeringMemberEntity`에서 새 도메인 객체를 생성(예를 들자면 `OfferingStatus` 객체 생성)하도록 하고, 그 객체에게 물어보는게 자연스러울 지 고민입니다..

2024-08-14 01:56 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
> +            @PathVariable(value = "offering-id") Long offeringId,
participations?offering-id={offering-id} 는 혹시 어떨까요! 클라 입장에선 participations/1 보단 participations?offering-id=1이 더 직관적이지 않을까 싶어 제안드려봅니다:) participations/1 은 약간 particpations/{participation-id}로 오해할 수도 있을 거 같아욥

2024-08-14 01:57 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
> +        return ResponseEntity.accepted().build();
delete 메서드에 응답 body가 없으니 204도 적절해 보이네요!

2024-08-14 01:57 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
> +
전 리브 좋은 거 같습니다!

2024-08-14 02:05 UTC, helenason requested changes
포케씨 수고하셨습니다

몇가지 리뷰 달아두었습니다!

다른 의견 갖고 계시면 언제든 달아주세용 ☺️

2024-08-14 02:05 UTC, masonkimseoul requested changes
간단한 수정 사항 남겼습니다~! 고생하셨어요.

2024-08-14 02:05 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +        CommentRoomStatus roomStatus = offering.getRoomStatus();
Offering의 상태는 OfferingMember까지 전이되는건 안된다고 생각합니다. 저도 이것에 대해 고민을 꽤 해봤는데, Offering을 가져오는게 젤 나을거 같긴 해요. 아직은 뾰족한 답을 못찾겠습니다.

2024-08-14 02:09 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +        CommentRoomStatus roomStatus = offering.getRoomStatus();
저도 offering에게 상태를 묻는 게 더 자연스러워 보입니다~

2024-08-14 02:38 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/domain/CommentRoomStatus.java
> +    }
[refactor: 모집중인 상태가 아닌 경우 공모 참여를 취소할 수 없도록 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/318/commits/8ca4ce3fd8edcdddeeeb8bb24ac879717948a560)

반영  했읍니다  ^__^

2024-08-14 04:22 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
> +        return ResponseEntity.accepted().build();
[refactor: 공모 참여 취소 응답 상태 코드 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/318/commits/f6b44660bb54fdf2d0e23189912341e36a049b61)

반영 완료 했읍니다 ^__^

2024-08-14 04:30 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
> +
일단, leave로 하다가, 부자연스러워 지면 리팩터링 하는 방향으로 가시죠 ~

2024-08-14 04:33 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/exception/OfferingMemberErrorCode.java
> +    CANNOT_CANCEL_IN_PROGRESS(BAD_REQUEST, "진행중인 공모는 참여를 취소할 수 없습니다.");
[refactor: 에러 메시지 명확한 문구로 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/318/commits/b5813170d99b7fed26f31029608b538c11fd9826)

반영 완료 했읍니다 ^__^

2024-08-14 04:34 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +        CommentRoomStatus roomStatus = offering.getRoomStatus();
넵 이건 그대로 둘게요~~

2024-08-14 04:35 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
> +            @PathVariable(value = "offering-id") Long offeringId,
너무 좋은데요? 반영하겠습니다~

2024-08-14 04:39 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
> +            @PathVariable(value = "offering-id") Long offeringId,
[refactor: query parameter를 적용해 어떤 공모의 참여를 취소할 것인지 의도를 명확하게 전달하도록 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/318/commits/b01b2cfbf837d552277f9fe61c6f1ecd4effba77)

2024-08-14 04:41 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +    }
`총대는 자신의 공모를 취소할 수 없다` 라는 도메인 규칙을 정의하였고 이에 맞춰 네이밍을 작성하다보니 해당 메서드가 나왔습니다~

메서드명으로 파악하기 어려우니 수정 하겠습니다~~

2024-08-14 04:42 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
> +    }
[refactor: 총대 검증 메서드 네이밍 명확하게 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/318/commits/cc5feac65c437554334600a2fe4fb1a10061012e)

2024-08-14 05:06 UTC, ChooSeoyeon approved these changes
lgtm 이요~ 고생하셧어요!

2024-08-14 05:49 UTC, masonkimseoul approved these changes
따봉 드립니다 👍

2024-08-14 06:20 UTC, helenason approved these changes
반영된 리뷰 모두 확인 완료!

포케가 리뷰 받고 싶은 부분을 먼저 언급해주어서 그 부분을 집중적으로 볼 수 있었어요!
좋은 방법인 것 같슴다 나도 나중에 따라해봐야지 허허

2024-08-14 06:49 UTC, merged