feat: 댓글방 생성 시점 변경
woowacourse-teams/2024-chongdae-market pull request #319
Opened 2024-08-13 12:11 UTC by helenason

## 📌 관련 이슈
close #316 
## ✨ 작업 내용
- 댓글방 생성 시점: 첫 참여 시점 -> 공모 생성 시점
- 댓글방 목록 API 리팩터링: 로그인한 사용자가 해당 댓글방의 총대인지 검증하는 로직
    - 기존: OfferingWithRole 도메인을 repository에서 생성해줌
    - 수정: 비즈니스 로직으로 처리
- 댓글 메시지 목록 API 리팩터링: 해당 메시지의 작성자가 해당 댓글방의 총대인지 검증하는 로직
    - 기존: CommentWithRole 도메인을 repository에서 생성해줌
    - 수정: 비즈니스 로직으로 처리
## 📚 기타

2024-08-13 12:16 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> +    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
`findCommentRoomsByMember` 메서드명 추천 받습니다.

위 쿼리는 `본인이 총대 혹은 참여자인 댓글방 목록을 조회하는 쿼리`입니다.

`findCommentRoomsByMember` 이름이 의미상 맞긴 한데, offeringRepository에 알맞은 용어라곤 생각하지 않아요. 우리가 사용하는 도메인 용어에 가깝다고 생각해서요.

탈락 리스트
1. findParticipatedOfferingsByMember -> 참여자에 한정된 이름 같아 제외
2. findRelatedOfferingsByMember -> 참여자 + 총대 라는 의미를 담고 싶은데 적절한 단어를 찾지 못함. related는 너무 추상적이라 제외

좋은 의견 있으면 남겨주세요~

2024-08-13 12:32 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> +    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
제가 코드를 놓친 거일 수도 있는데, 메서드명으로 예측할 수 있는 반환값은`List<CommentRoom>`이라고 생각했는데 `List<OfferingEntity>`를 반환하는 이유가 있나요? 😃 

메서드명과 반환값이 달라서 혼란스러웠습니다. 단순하게 `findOfferingsBymember`는 어떤가요?

2024-08-13 12:39 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.equals(member));
equals는 범용적으로 사용하는 메서드라고 생각하는데, member.isSameMember를 사용하지 않은 이유가 있을까요? 😄

2024-08-13 13:13 UTC, fromitive requested changes
에버 고생많으셨어요~~

댓글방 생성 시점 변경 로직과 댓글방 목록 조회 시 마지막 댓글 반환 로직도 읽기 불편함이 없었어요 😃 

달아주신 네이밍에 대해서도 의견을 달았고, 코드 관련하여 약간의 코멘트 달았으니 확인부탁드려요!! 😄 

화이팅이에요~

2024-08-14 02:11 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.equals(member));
저도 tda 관점에서 봤을 때 getter로 빼와서 확인하는 것보단 물어보는 게 나을 거 같네요! comment.getmember.equals(member) 보다 comment.isOwnedBy(member) 와 같이요!

2024-08-14 02:13 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.getNickname(),
comment.getIssuerNickname() 도 괜찮겠네용~

2024-08-14 02:18 UTC, masonkimseoul requested changes
고생하셨습니다! 코멘트 확인해주세요~

2024-08-14 02:18 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
> +    List<CommentEntity> findAllByOfferingOrderByCreatedAt(OfferingEntity offering);
damn clean~

2024-08-14 02:18 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.getNickname(),
@fromitive 근데 이 부분에서 commentWriter는 MemberEntity라 getIssuedNickname보다는 getNickname이 맞는 것 같아요.

2024-08-14 02:18 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> +    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
넓은 의미로 봤을 때 Proposer도 Offering에 Participate 한 상태이니까 괜찮지 않을까요?
저는 1번 `findParticipatedOfferingsByMember` 좋은 것 같습니다.

2024-08-14 02:20 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +    private CommentAllResponseItem toCommentAllResponseItem(CommentEntity comment, MemberEntity member) {
이 메서드를 CommentAllResponseitem 의 생성자로 만드는 건 혹시 어떨까요~ 
```
CommentAllResponseItem(CommentEntity comment, MemberEntity member) {
    this(comment.getId(), ...)
}
```

위 방식의 장점은 변경이 잦은 dto 필드의 특성을 고려했을 때 서비스 코드의 변경을 최소화할 수 있단 점이 있을 거 같아요!
현재 방식을 택한 에버의 이유가 궁금합니당

2024-08-14 02:31 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> +    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
만일 offeringEntity가 oneToMany로 `List<OfferingMemberEntity> offeringMembers`를 가지고 있다면, findByOfferingMembers_member() 와 같이 명시해 jpql 없이 해결 가능했겠군요. 물론 저는 양방향 지양하는 편이라 이방식은 추천하지 않습니다. 다만, 저런식으로도 이름을 지을 수 있다는 아이디어 제시 정도의 커멘트 남기고 갑니당. 개인적으로 지금 이름 직관적이라 좋은 거 같아요~ 포케가 말한 이름도 좋네요!

2024-08-14 04:27 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> +    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
@ChooSeoyeon 그런 방법이 있겠네요! 일단 우리 코드는 단방향을 기준으로 작성하고 있어 위와 같이 코드를 작성하였습니다. 좋은 의견 고마워요! :)

---
이름 관련하여서는 세분의 의견이 모두 다른 것으로 보아 취향 차이인 것으로 판단하였습니다. 현재 상태 유지하겠습니다!

2024-08-14 04:36 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.equals(member));
동의합니다!

OfferingEntity에서 isProposedBy() 메서드를 선언한 맥락과 동일하게 isOwnedBy로 대체하였습니다.

추가로, MemberEntity에 isSame() 메서드 추가하였습니다~

2024-08-14 04:52 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.getNickname(),
비슷한 맥락의 이전 [코멘트](https://github.com/woowacourse-teams/2024-chongdae-market/pull/319#discussion_r1715223669)에 대해서는 충분히 납득하였으나, 해당 코멘트에 대해서는 조금 다른 의견을 가지고 있습니다!

댓글이 로그인멤버를 받아 본인의 소유자가 맞는지 파악하는 흐름은 자연스럽지만,
댓글이 소유자의 닉네임을 반환하는 것은 조금 어색하다고 생각해요!

따라서, 현재의 흐름을 유지할까 합니다! 추가 의견 있으시면 언제든 코멘트 더 달아주세용 ~~~

2024-08-14 04:54 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
> +    List<CommentEntity> findAllByOfferingOrderByCreatedAt(OfferingEntity offering);
감사합니다. 저 짧은 두 단어가 꽤 큰 힘이 되네요?

2024-08-14 04:59 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +    private CommentAllResponseItem toCommentAllResponseItem(CommentEntity comment, MemberEntity member) {
오! 안 그래도 위에서 다른 리뷰 반영하면서 같은 방식으로 리팩터링하고 오는 길이에요! (불과 2주 전 작성한 코드가 legacy가 되어버린..)

저의 생각과 같은 코멘트를 보니 반갑네요~ 제 방향에 더더욱 확신을 갖게 되었어요. 좋은 의견 고마워요 ㅎㅎ

2024-08-14 05:07 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> +    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
[refactor: 댓글의 작성자 확인 메서드 추가](https://github.com/woowacourse-teams/2024-chongdae-market/pull/319/commits/eb51dc0e0e9aa6194eedc9f6aa8961f6c1312a49)

2024-08-14 05:07 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +                commentWriter.equals(member));
[refactor: 댓글의 작성자 확인 메서드 추가](https://github.com/woowacourse-teams/2024-chongdae-market/pull/319/commits/eb51dc0e0e9aa6194eedc9f6aa8961f6c1312a49)

2024-08-14 05:52 UTC, fromitive approved these changes
에버 코드 잘 봤고~~ 의견 감사합니다~ lgtm입니당 ㅎㅎ

2024-08-14 05:53 UTC, masonkimseoul approved these changes
잘 읽었습니다. LGTM~ 👍

2024-08-14 06:49 UTC, merged