feat: 로그인 API 응답에 memberId와 nickname 필드 추가
woowacourse-teams/2024-chongdae-market pull request #322
Opened 2024-08-13 13:39 UTC by ChooSeoyeon

## 📌 관련 이슈
close #321 
## ✨ 작업 내용
- 로그인 API 응답에 memberId와 nickname 필드 추가
## 📚 기타

2024-08-13 13:52 UTC, ChooSeoyeon commented
아직 완료 x 리팩토링중

2024-08-13 17:09 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/auth/service/dto/AuthMemberDto.java
> +public record AuthMemberDto(Long id, String nickname) {
id가 필요한 상황이 있었을까요? 😃 인증 토큰으로 어떤 memberId인지 확인할 수 있지 않나요?

2024-08-14 02:21 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/auth/service/dto/AuthMemberDto.java
> +public record AuthMemberDto(Long id, String nickname) {
안드 측의 요청이었습니다! 정확하겐 하나의 소셜로그인 계정으로 여러 디바이스에서 로그인할 수 있는데, 첫 회원가입 이후 다른 기기에서 로그인할 때 memberId와 nickname 받을 방법이 없어서 추가하게 되었습니다!

2024-08-14 02:23 UTC, masonkimseoul approved these changes
고생하셨습니다. 특별히 고칠만한 부분은 전 없는 것 같아요~

2024-08-14 02:25 UTC, helenason requested changes
도라씨 수고했습니다~~~~

다른 의견 있으시면 추가 코멘트 남겨주세용

2024-08-14 02:25 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/auth/controller/AuthController.java
>      }
제가 저번에 제안드렸던 방식은 혹시 고려해보셨나용? HttpServletResponse를 사용하지 않고 쿠키를 응답에 담는 방식이요~

HttpServletResponse 객체가 많아지면서 코드의 가독성이 낮아지는 것 같은데,
저번에 제안드렸던 방식이 적용 불가능해서 적용하지 않으신 건지, 가능하지만 잠깐 미뤄두신 건지 궁금합니다~

가능한 방법이라면 이번 기회에 적용해보는 것은 어떨까요?

2024-08-14 02:25 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/auth/controller/AuthController.java
>              @RequestBody SignupRequest request, HttpServletResponse servletResponse) {
`@Valid` 어노테이션을 통해 검증을 진행해주세요~~~!

2024-08-14 04:55 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/auth/controller/AuthController.java
>      }
쿠키가 여러 개일 때도 제안해주신 방식을 사용하는 게 가능한지 못찾겠어서 미뤄두었습니다.

2024-08-14 04:59 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/auth/controller/AuthController.java
>              @RequestBody SignupRequest request, HttpServletResponse servletResponse) {
[feat: valid 어노테이션 추가](https://github.com/woowacourse-teams/2024-chongdae-market/pull/322/commits/d4314f4d6fec46176626626c4ab9c7535b77e954)

2024-08-14 06:50 UTC, merged