feat: 공모 상세 조회 API 응답에 총대여부 알려주는 boolean 필드 추가
woowacourse-teams/2024-chongdae-market pull request #323
Opened 2024-08-13 15:01 UTC by ChooSeoyeon

## 📌 관련 이슈
close #320 
## ✨ 작업 내용
- 공모 상세 조회 API 응답에 총대여부 알려주는 boolean 필드 추가
## 📚 기타

2024-08-13 15:08 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
>          OfferingStatus offeringStatus = offering.toOfferingStatus();
과거 저희가 entity에 toDomain 함수를 넣었던 이유는 
계층 구조를 '(상위) Controller > Service > Repository & Entity > Domain (하위)'로 생각했기 때문입니다.
'상위는 하위를 알되, 하위는 상위를 모르게 한다' 원칙에 입각했을 때 Entity가 차라리 domain의 필드를 알고 사용하는 게 타당해보였죠.

다만,,, 지금시점에서 다시 바라봤을 땐 계층구조를 저희가 잘못생각한 게 아닐까? 하는 의문이 듭니다.
일단 G선생님은 '(상위) Controller > Service > Domain > Repository > Entity (하위)'라고 말씀하시는데 같이 관련 레퍼런스 찾아보면 좋을 거 같습니다.

만일 저희가 계층관계를 반대로 생각한거라면 
entity 내부의 toDomain 함수를 전부 제거한 후, 
domain의 생성자가 entity를 받는 구조로 리팩토링해야 할 거 같습니다!

2024-08-13 17:17 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
>          OfferingStatus offeringStatus = offering.toOfferingStatus();
> domain의 생성자가 entity를 받는 구조로 리팩토링해야 할 거 같습니다!
domain생성자의 매개변수로 entity를 받는 구조는 찬성입니다~ 😄

2024-08-13 17:19 UTC, fromitive commented on backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
> +            offeringMemberFixture.createProposer(proposer, offering);
fixture 요긴하게 잘 쓰고 있습니다 감사합니다 👍

2024-08-14 02:29 UTC, masonkimseoul approved these changes
고생하셨습니다~ 이 PR도 딱히 흠잡을만한건 안보이네요.
변환로직에 대해선 차차 고칩시다.

2024-08-14 02:29 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +        OfferingProductImageResponse response = offeringService.extractProductImageFromOg(request);
👍

2024-08-14 02:29 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
>          OfferingStatus offeringStatus = offering.toOfferingStatus();
엔티티의 변환 로직을 도메인으로 옮겨야겠군요~
대대적인 공사가 되겠습니다.

2024-08-14 02:36 UTC, helenason requested changes
도라 수고했어요~~

몇가지 수정사항 요청했어요.

반영하시고 코멘트 주세요!

2024-08-14 02:36 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
>      }
저도 위 메서드 `isProposedBy`를 두 PR 모두에 추가하였는데요.

아래와 같이, 선언한 메서드를 잘 활용하는 것이 좋아보입니다!

현재 코드에 반영은 안 하셔도 되고, 나중에 머지할 때 제 코드를 반영해주시면 될 것 같아요~

```java
public boolean isProposedBy(MemberEntity other) {
    return this.member.equals(other);
}

public boolean isNotProposedBy(MemberEntity other) {
    return !isProposedBy(other);
}
```

2024-08-14 02:36 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
>          OfferingStatus offeringStatus = offering.toOfferingStatus();
저도, dto가 도메인 또는 엔티티를 받아 본인 객체를 생성하듯이, 도메인도 마찬가지로 엔티티를 받아 스스로를 생성하게 하는 것이 나아보입니다! 그 경우 엔티티 또한 지금보다 더욱 가벼워지고 필요한 로직만 남겠네요!

모든 PR 머지시키고 전체적으로 진행하면 좋을 것 같슴당

2024-08-14 02:36 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingDetailResponse.java
> +                                     Boolean isProposed,
현재, 총대 여부를 나타내는 응답 필드는 `isProposer`라는 이름을 사용하고 있어요!
모든 응답들과 통일하여 `isProposer`로 변경하는 것이 어떨까요?

2024-08-14 04:46 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingDetailResponse.java
> +                                     Boolean isProposed,
바로 아래 필드인 isParticpated 와 통일성을 주고자 isProposed 라 이름붙이긴 했습니당 아래도 같이 isParticipated 으로 바꾸겠습니다!

2024-08-14 04:58 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingDetailResponse.java
> +                                     Boolean isProposed,
[feat: 공모자 여부 필드명 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/323/commits/8018da74856bd336cee7a81f74d5ddbf8801b017)

2024-08-14 06:23 UTC, helenason approved these changes
lgtm이용 굿!

2024-08-14 06:52 UTC, merged