feat: 거래 날짜 검증 로직 추가
woowacourse-teams/2024-chongdae-market pull request #471
Opened 2024-09-04 05:02 UTC by masonkimseoul

## 📌 관련 이슈
close #470 
## ✨ 작업 내용
- 거래 날짜 검증 로직 추가
- 테스트 코드 추가
## 📚 기타

2024-09-04 08:38 UTC, helenason requested changes
한군데 정도 같이 고민해보면 좋을 포인트 적어두었어요!
생각해보시고 답장주세yo

2024-09-04 08:38 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
>          // TODO : 각자 맡은 팀에서 계산하는 로직 생각하기, 객체로 빼서 만드셈~
혹시 이 주석 친구도 함께 삭제해주실 수 있나yo

2024-09-04 08:38 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
> +    }
저는 `거래 날짜를 내일부터로 설정 가능하다`는 조건이 서비스(비즈니스) 로직이라고 생각해요!
따라서 DTO 보다는 서비스 내에서 검증하는 방식이 좋다고 생각합니다. 어떻게 생각하시나요 ~~~~~ 😃

2024-09-04 08:38 UTC, helenason commented on backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
> +        @DisplayName("거래 날짜를 내일보다 과거로 설정하는 경우 예외가 발생한다.")
테스트 작성까지 👍 짱짱맨들

2024-09-04 12:06 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
> +    }
에버의 말에 매우 동의합니다~

2024-09-04 12:08 UTC, ChooSeoyeon approved these changes
거래 날짜 검증 로직 위치 말곤 따로 피드백 할 부분 없슴다 고생하셨습니다!

2024-09-23 08:07 UTC, helenason approved these changes
lgtm

2024-09-23 08:07 UTC, merged