feat: 공모 수정 API 구현
woowacourse-teams/2024-chongdae-market pull request #485
Opened 2024-09-12 08:17 UTC by fromitive

## 📌 관련 이슈
close #484
## ✨ 작업 내용

안녕하세요 선생님들 공모 수정 API 구현 완료했습니다. 

생각하지 못한 조건들이 많아서 궁금한 부분들은 코멘트 달아놓겠습니다~ 

공모 수정 시 이전에 회의한 비즈니스 검증 로직을 적용했고, 테스트 코드도 빵빵하게 넣었습니다. 😄 

## 📚 기타

2024-09-12 08:18 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +            @RequestBody @Valid OfferingModifyRequest request,
`OfferingModify`, `OfferingUpdate` 네이밍 고민인데 어떤걸로 하는게 좋을까요?

2024-09-12 08:19 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingPrice.java
> +    public void validateOriginPrice() {
수정 시 n빵가격 검증이 필요해서 public으로 오픈했습니다 😃

2024-09-12 08:22 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateOriginPrice(request);
totalPrice는 unmodified하게 하는게 확정이었나요 ?_? 확정이라면 검증로직 수정하겠습니다~

2024-09-23 04:38 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +            @RequestBody @Valid OfferingModifyRequest request,
저는 개인적으로 OfferingUpdate 좋은 것 같습니다!

2024-09-23 04:43 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +            @RequestBody @Valid OfferingModifyRequest request,
저도 update 좋은 것 같습니다

2024-09-23 04:44 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateOriginPrice(request);
수정 가능인 것 같네요~

2024-09-23 04:48 UTC, masonkimseoul requested changes
고생하셨습니다. 몇 가지 코멘트 남겼습니다!

2024-09-23 04:48 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +
개행 하나만 지워주세요~

2024-09-23 04:48 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        Integer modifiedCount = request.totalCount();
int 말고 Integer을 사용한 이유가 있나요?

2024-09-23 05:04 UTC, helenason requested changes
포케 수고했습니다아아아

가장 빠르게 코드 구현을 해주셔서 대단하다고 생각했습니닷

몇가지 리뷰 남겨드렸으니 확인해보시고 반영 여부 결정해주세요!

제가 참고한 수정 정책은 아래와 같습니다.

- 인원 확정전까지 수정 가능
- total count는 현재 인원 이상만 가능
- meeting date는 내일 이상만 가능

2024-09-23 05:04 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +        return ResponseEntity.ok().build();
다른 수정 API의 경우 수정된 데이터 정보를 response body를 통해 전달하고 있는데요. 위 API도 마찬가지로 수정된 데이터를 전달하는 것이 어떨까요? 😊

2024-09-23 06:23 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateOriginPrice(request);
현황 유지 할게요 😄

2024-09-23 06:26 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        Integer modifiedCount = request.totalCount();
Integer가 Nullable 할 수 있어서 정보가 없으면 기본값을 저장하는 int와 다르게 `정보를 담고 있지 않음`을 표현하고 싶었어요 😃

2024-09-23 06:40 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +    }
이건 좀 고민해봐야 할 것 같아요~~
제 생각은 **OfferingModifyRequest에 수정 가능한 필드만 명시해서 수정해야 한다**고 생각합니다아아

`toEntity`로 Entity로 변환하는 순간 수정에 사용하지 않는 `OfferingStatus.AVAILABLE` 과 `CommentRoomStatus.GROUPING`을 넣여야 하니깐요 😢 

하지만 에버 관점도 좋은 관점이라고 생각합니다! offeringPrice에 validate 부분을 public으로 열지 않아도 되고, 검증 로직을 간편하게 가져간다는 점에서요~ 

한 번 적용해보고 다시 한 번 봐주실 수 있을까요~~

2024-09-23 06:54 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        if (modifiedCount <= currentCount) {
인원이 만석일 경우 총원 을 수정하지 않아도 예외가 발생하겠군요..! 관련 테스트 추가하고 등호 제거하겠습니다 😄

2024-09-23 07:02 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
> +    }
매우매우 동의합니다,,! requestDto가 entity에 침투하는 건 바깥의 웹계층이 내부로 침투하는 것과 마찬가지라 생각합니다.

2024-09-23 07:03 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +            @RequestBody @Valid OfferingModifyRequest request,
저도 update요!

2024-09-23 07:04 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        if (modifiedDate.isBefore(today) || modifiedDate.isEqual(today)) {
공모 생성 규칙이 `거래 당일` 에 대한 공모를 생성할 수 없어서요~ 해당 부분은 남겨 두는게 좋을 것 같습니다~~
---
테스트 결과 400 나오는게 맞아요~

2024-09-23 07:04 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateTotalCount(offering, request);
오우 좋은데요?

2024-09-23 07:06 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateMeetingDate(request);
request를 전달하기보단, request의 필드를 풀어서 전달하는 건 어떨까요? Web 계층의 dto로 사용하던 requestDto가 serivce 클래스 private 메서드들의 인자로 여러 번 돌아다니는 것보단, public 메서드 인자로 딱 한 번만 들어오는 편이 바람직하다 생각합니다

2024-09-23 07:09 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateMeetingDate(request);
좋은데요?

2024-09-23 07:14 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +    }
```
public OfferingEntity toEntity(MemberEntity member) {
    OfferingPrice offeringPrice = new OfferingPrice(totalCount, totalPrice, originPrice);
    Double discountRate = offeringPrice.calculateDiscountRate();

    return new OfferingEntity(member, title, description, thumbnailUrl, productUrl, meetingDate, meetingAddress,
            meetingAddressDetail, meetingAddressDong, totalCount, 1,
            totalPrice, originPrice, discountRate, OfferingStatus.AVAILABLE, CommentRoomStatus.GROUPING);
}
```

이 코드 의도 좋습니다. 다만, 비즈니스 로직이 dto에 위치한 점이 아쉽네요. 말씀해주신 코드 아래처럼 리팩토링하면 좋을 거 같은데 어떻게 생각하시나요. @helenason 
```
public OfferingEntity toEntity(OfferingPrice offeringPrice, Double discountRate) {
    return new OfferingEntity(member, title, description, thumbnailUrl, productUrl, meetingDate, meetingAddress,
            meetingAddressDetail, meetingAddressDong, totalCount, 1,
            totalPrice, originPrice, discountRate, OfferingStatus.AVAILABLE, CommentRoomStatus.GROUPING);
}
```

2024-09-23 07:16 UTC, ChooSeoyeon commented on backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
> +                MemberEntity participant = memberFixture.createMember("poke_%d".formatted(i));
for (int i = 0; i < 9; i++) { createMember("poke_%d".formatted(i)); }
 
 이 부분 로직 fixture 내부로 넣는 건 어떨까요?

2024-09-23 07:28 UTC, fromitive commented on backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
> +                MemberEntity participant = memberFixture.createMember("poke_%d".formatted(i));
한 번 넣어보겠습니다~

2024-09-23 07:35 UTC, fromitive commented on backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
> +                MemberEntity participant = memberFixture.createMember("poke_%d".formatted(i));
반영 완료~

[feat: createMembers 기능 구현](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/a2900b6cda51fd52cd3897a01b9c78aa48057654)

2024-09-23 07:35 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateMeetingDate(request);
반영 완료! 의도와 맞는지.. 한 번 확인 부탁드려요!!

[refector: 검증 로직의 매개변수를 검증하는 대상을 알 수 있도록 구체화](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/4018ff02adb28b0ce858ca9ac90ff652638a333d)

2024-09-23 07:36 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +        return ResponseEntity.ok().build();
반영 완료! **응답 필드가 적절한지 확인 부탁드릴게요!**

[feat: 수정 성공 시 수정 된 내용을 반환하는 기능 구현](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/7740d2356f555dcee16fe3132b75527e93c3030c)

2024-09-23 07:36 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
> +    }
반영 완료했어요~ 이제 `OfferingModifyRequest`에 대한 의존은 사라졌어요 😄  확인 부탁드립니다~

[refactor: offeringUpdateRequest 의존 제거](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/ae3c344dd1b252305dba0fff7e6a5047d4311aec)

2024-09-23 07:37 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        validateTotalCount(offering, request);
반영 완료! 의도와 맞는지.. 한 번 확인 부탁드려요!!

[refector: 검증 로직의 매개변수를 검증하는 대상을 알 수 있도록 구체화](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/4018ff02adb28b0ce858ca9ac90ff652638a333d)

2024-09-23 07:38 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +    }
넵 좋습니다! 하지만 말씀 드렸듯 위 코드는 OfferingSaveRequest 클래스에 존재하는 메서드를 첨부한 것입니다. 따라서 두 메서드 모두 함께 리팩터링 진행하면 좋겠네요 :)

2024-09-23 07:39 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        if (modifiedCount <= currentCount) {
반영 완료했어요~

[fix: 참여 인원이 만석일 때 수정하지 못하는 버그 해결](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/4cc4282221f34d6eb911aeb85431d48b222033da)

2024-09-23 07:43 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +    }
아래는 수정한 커밋인데요, 이건 다 같이 고민해봐야 할 것 같아요! 
수정되지 않아야 할 필드를 위해 `OfferingEntity`에 또 다른 생성자를 추가하면 생성자가 무거워지고
수정에 사용하지 않은 필드에 더미데이터를 집어 넣는 것은 실수의 여지가 있어보이는데, 그냥 테스트를 더 보강해서 극복할지 아니면 좀 더 좋은 리펙터링을 할지 고민됩니다~

[refactor: offeringUpdateRequest 의존 제거](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/ae3c344dd1b252305dba0fff7e6a5047d4311aec)

2024-09-23 07:43 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        Integer modifiedCount = request.totalCount();
반영 완료!!!!!!!!!!!!!
[style: 불필요한 개행 제거](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/75bbef235518c9f1caa5b51f8a6f1067288fc196)

2024-09-23 07:44 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +
반영 완료!!!!!!!!!!!!!~~~
[style: 불필요한 개행 제거](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/75bbef235518c9f1caa5b51f8a6f1067288fc196)

2024-09-23 07:44 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
> +            @RequestBody @Valid OfferingModifyRequest request,
반영 완료했습니다 😄 

[refactor: 공모 수정 modify -> update로 변경](https://github.com/woowacourse-teams/2024-chongdae-market/pull/485/commits/def1c7a0e3cfa8a4c7438c7cfea6d9d146235893)

2024-09-23 07:57 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingUpdateRequest.java
> +        Double discountRate = offeringPrice.calculateDiscountRate();
``` 
OfferingPrice offeringPrice = new OfferingPrice(totalCount, totalPrice, originPrice);
Double discountRate = offeringPrice.calculateDiscountRate();
```

위 두줄은 Service 로 빼면 어떨까요!? 현재엔 비즈니스 로직이 dto에 들어가 있어서 후에 관리하기 어려울 거 같습니다.

2024-09-23 08:00 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
> +    public void update(OfferingEntity request) {
변수명 request 말고 updatedOffering 은 어떤가용

2024-09-23 08:15 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
> +    public void update(OfferingEntity request) {
추가로, OfferingEntity가 아니라 UpdatedOffering 같은 도메인을 사용하면 훨씬 좋을 거 같네요!! (사용안할값들 일부러 null 안넣어도 됨)

2024-09-23 08:49 UTC, helenason approved these changes
lgtm

2024-09-23 08:49 UTC, masonkimseoul approved these changes
👍

2024-09-23 08:55 UTC, merged