feat: 채팅방 조회 시 soft delete 된 공모 별도 처리
woowacourse-teams/2024-chongdae-market pull request #502
Opened 2024-09-26 04:33 UTC by ChooSeoyeon

## 📌 관련 이슈
close #497 

## ✨ 작업 내용
- 채팅방 상세 조회 시 soft delete 여부 알려주는 플래그 추가
- 채팅방 목록 조회 시 삭제된 공모 별도 처리

## 📚 기타
- offeringMember를 조회할 때 soft delete된 offering 에 의해 조회되지 않는 문제가 발생해, offeringMember와 offering 사이에 조인 전략을 eager에서 lazy로 변경해 해결했습니다.
- offeringMember를 통해 offering을 조회해 올 때 조인 전략이 lazy일 땐 세션이 유지된 상태여야 하기 때문에, transactonl(readonly=true)적용이 필요했습니다.

2024-09-26 04:34 UTC, fromitive approved these changes
lgtm!

2024-09-27 08:36 UTC, masonkimseoul requested changes
고생하셨습니다.
코멘트 확인 부탁드려요!

2024-09-27 08:36 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRepository.java
> +            """, nativeQuery = true)
왜 nativeQuery를 사용하셨나요? 궁금합니다.

2024-09-27 08:36 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java
> +    @ManyToOne(fetch = FetchType.LAZY)
게으르네요;;

2024-09-27 08:36 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
> +    Optional<CommentEntity> findTopByOfferingIdOrderByCreatedAtDesc(Long offeringId);
~OfferingOrder~ 에서 ~OfferingIdOrder~로 바꾼 이유가 있나요?

2024-09-27 08:36 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +        return comment.map(CommentLatestResponse::new)
메서드가 좀 더 명확해진 것 같네요

2024-09-27 08:36 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +        boolean isProposer = offeringMember.isProposer(); // TODO : 도메인으로 정리
언젠가... 언젠가 해야한다

2024-09-27 08:36 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomAllResponseItem.java
> +                offeringMember.isProposer(),
Get 해야 하는 depth가 늘어났네요. 이런 선택을 하게 된 이유가 궁금합니다. 막 반드시 수정하란 의미까지는 아니고... 왜 OfferingMember여야 했는지?

2024-09-27 09:02 UTC, helenason requested changes
수고하셨습니다! 리뷰 반영 부탁드려요~~~~

2024-09-27 09:02 UTC, helenason commented on backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java
> +        @DisplayName("존재하지 않는 공모 id로 댓글방 정보를 조회할 경우 예외가 발생한다.")
유효하지 않은 공모(DB에 없는 공모)와 삭제된 공모(DB에 존재하지만 soft delete)에 대해 테스트를 나누어 작성하는 것이 어떨까요?

2024-09-27 09:12 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java
> +    @ManyToOne(fetch = FetchType.LAZY)
우우

2024-10-03 18:19 UTC, ChooSeoyeon commented on backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java
> +        @DisplayName("존재하지 않는 공모 id로 댓글방 정보를 조회할 경우 예외가 발생한다.")
둘의 상태코드가 같기에 integrationTest에서 책임질 영역은 아니라고 판단했습니다. 따라서 serivceTest에만 말씀해주신 테스트 작성해두었습니다.

2024-10-03 18:39 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRepository.java
> +            """, nativeQuery = true)
작성 당시 아래와 같은 이유로 nativeQuery를 사용했었습니다.

> nativeQuery를 쓰지 않으면 jpa의 엔티티그래프 탐색 방식을 따르게 됩니다. 따라서 offeringMember -> offering -> offeringId 순으로 찾아오게 되는데요. 이때 soft delete된 offering은 찾아오지 못하게 됩니다. 따라서 nativeQuery로 offeringMember -> offeringId 를 바로 찾아오도록 유도했습니다.

다만 지금 다시 확인해보니(초기 상태와 같이 eager로 돌린 채 테스트해봤습니다) 
꼭 native query를 쓰지 않아도 offeringMember -> offeringId를 바로 찾아오네요..?
```
Hibernate: 
    select
        ome1_0.offering_id 
    from
        offering_member ome1_0 
    where
        ome1_0.member_id=?
```

작성 당시 당연히 엔티티그래프를 탈줄 알았는데, 메이슨 덕분에 교차검증 해볼 수 있었습니다! 감사해요~~
nativeQuery는 지우겠습니다:)

2024-10-03 18:45 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
> +    Optional<CommentEntity> findTopByOfferingIdOrderByCreatedAtDesc(Long offeringId);
softDelete된 공모에 대한 comment를 찾아올 땐 offering이 아닌 offeringId로 찾아와야 했기 때문입니다.

2024-10-03 18:46 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomAllResponseItem.java
> +        this(offeringId,
offeringMember.getOffering.getId()를 하게 되면 삭제된 offering일 땐 에러가 발생하기 때문입니다.

2024-10-03 18:49 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomAllResponseItem.java
> +                offeringMember.isProposer(),
offeringMember를 어차피 넘겨줘야 하는데, 그 내부의 것을 까서 넘겨줄 필요 없다 생각했습니다.

2024-10-03 19:01 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomInfoResponse.java
> +        DELETED_VIEW(DELETED, imageUrl("DELETED"), "삭제된 공고", "삭제된 공동구매입니다."),
이미지 디자인 나오면 바로 넣겠습니다! 이 부분 회의 때 같이 이야기해보아야 할듯요

2024-10-03 19:16 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
> +
헉 너무 좋은걸요! 반영했습니다!

2024-10-07 04:15 UTC, helenason approved these changes
수고하셨습니다!

2024-10-07 04:15 UTC, masonkimseoul approved these changes

2024-10-07 04:21 UTC, merged