feat: AOP 적용해 읽기/쓰기 DB로 요청 분산
woowacourse-teams/2024-chongdae-market pull request #503
Opened 2024-09-26 12:41 UTC by ChooSeoyeon

## 📌 관련 이슈
close #498 
## ✨ 작업 내용
- AOP 적용해 읽기/쓰기 DB로 요청 분산
    - WriterDatabase 어노테이션 사용 시 writerDataSource 사용
    - WriterDatabase 어노테이션 사용 안할 시 readerDataSource 사용

## 📚 기타
- Datasource 설정 분리
- WriterDatabase 어노테이션 생성
- AOP 적용해 Datasource 동적 변경

2024-09-27 08:44 UTC, masonkimseoul requested changes
고생하셨습니다.
코멘트 확인해주세요.

2024-09-27 08:44 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +public class DataSourceConfig {
이 클래스도 궁금합니다.

2024-09-27 08:44 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceRouter.java
> +    private static final ThreadLocal<String> contextHolder = new ThreadLocal<>();
쓰레드 로컬을 도입한 이유가 궁금합니다.

2024-09-27 08:44 UTC, masonkimseoul commented on backend/src/main/resources/application-prod.yml
> +      ddl-auto: none
이 옵션을 none으로 설정한 이유가 있을까요?

2024-09-29 12:58 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceAspect.java
> +    }
아래의 서비스가 있다고 가정해봐요 😄 

```java
@WriterDatabase
public Response save(Request request) { 
    Entity entity = new Entity(request);
    Result result = Repository.save(entity)
    return new Response(result);
}
```

1. controller에서 `save` 메서드를 호출할 할 때 `@WriterDatabase` 어노테이션을 인식하게 됩니다. 
2. `setWriterDataSource`가 호출되서 데이터 소스가 `write`로 변경됩니다. 이렇게 되면 Repository.save 할 때 writer DB로 설정한 DBMS에 쿼리가 실행됩니다.
3. `save` 메서드가 종료 된 후 `@After` 어노테이션 붙은 `setReaderDataSource`가 호출되어 데이터 소스가 다시 `read`로 변경되는 구조에요~

2024-09-29 12:59 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +@EnableJpaRepositories(basePackages = "com.zzang.chongdae")
EnableJapRepository는 왜 붙여지게 된건가요? 필요없지 않나요??

2024-09-29 13:04 UTC, fromitive commented on backend/src/main/resources/application-prod.yml
> +      ddl-auto: none
다시 validate로 설정해도 되겠는데요? 테스트하다가 누락된 것으로 보입니다

2024-10-04 05:55 UTC, helenason requested changes
코드 잘 봤습니다!

Spring AOP, DB 분리 등 생소한 개념들이라 재밌게 했네요 :)

관련하여 질문이랑 제안 남겨두었으니 확인 부탁 드립니다~~~

2024-10-04 05:55 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceRouter.java
> +    private static final ThreadLocal<String> contextHolder = new ThreadLocal<>();
+) contextHolder는 멀티스레드 환경에서 스레드별 데이터소스를 지정하기 위한 용도가 맞나요?

2024-10-04 05:55 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +@RequiredArgsConstructor
Config 파일에 생성자는 왜 필요한 건가용?

2024-10-04 05:55 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +        return DataSourceBuilder.create().type(HikariDataSource.class).build();
[질문] 위와 같이 빌더를 통해 데이터소스를 생성하는 방식과 `new HikariDataSource()`와 같이 생성자를 통해 직접 생성하는 방식의 차이가 궁금해요!

2024-10-04 05:55 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +}
[질문] LazyConnectionDataSourceProxy 클래스로 감싼 데이터소스를 사용하는 이유는 성능 때문이 맞나요? (데이터 소스에 대한 연결이 실제로 필요할 때까지 지연되어 성능 최적화에 도움)

[제안] 코드의 흐름상 메서드 구현 순서가 역순이 되면 더 자연스럽지 않을까 싶은데, 어떻게 생각하시나요? 어차피 `@DependsOn`을 통해 빈 초기화 순서를 지정하고 있기 때문에 주요 빈을 먼저 선언하는 게 좋을 것 같아요! (dataSource -> routeDataSource -> writeDataSource -> readDataSource)

2024-10-04 05:55 UTC, helenason commented on backend/src/main/resources/application.yml
> +    open-in-view: false
해당 속성이 true로 설정되어 있을 때 어떤 문제가 발생했는지 공유해주시면 감사하겠습니다 :)

2024-10-04 07:42 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceRouter.java
> +    private static final ThreadLocal<String> contextHolder = new ThreadLocal<>();
각 API 요청마다 reader, writerdb 를 구분하기 위해 ThreadLocal을 도입했습니다. 

멀티스레드 환경에서 스레드 단위로 변수(`contextHolder`)를 만들 수 있어요.

DataSourceRouter는 상태가 **있는** 객체이고 `@Bean`으로 등록되어 있기 때문에 요청을 처리하는 쓰레드들이 현재 설정되어 있는 dataSource를 공유하는 구조가 되어버립니다 😢 

그래서 ThreadLocal을 활용하여 아래처럼 각 요청마다 dataSource를 설정할 수 있도록 변경했어요..!

<img width="612" alt="image" src="https://github.com/user-attachments/assets/fbdc6274-f530-4e1c-a01b-64e6f0e042ca">

2024-10-07 04:31 UTC, ChooSeoyeon commented on backend/src/main/resources/application-prod.yml
> +      ddl-auto: none
이부분은 추후 ci 스크립트 넣어서 validate 미리  사용해봐도 좋을 거 같네요~

2024-10-07 04:43 UTC, masonkimseoul approved these changes

2024-10-07 04:46 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +        return DataSourceBuilder.create().type(HikariDataSource.class).build();
큰 차이 없는 것 같습니다. 가독성 측면에서 이 방법이 더 좋을 것 같아요.

2024-10-07 04:47 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +@EnableJpaRepositories(basePackages = "com.zzang.chongdae")
필요 없는 것으로 판결

2024-10-07 04:50 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/global/config/DataSourceConfig.java
> +}
성능을 위해 사용하는 것 맞습니다. (LazyConnectionDataSourceProxy)
제안해주신 방안은 적용하겠습니다.

2024-10-07 04:56 UTC, fromitive commented on backend/src/main/resources/application.yml
> +    open-in-view: false
Open session in view 가 true일 경우 view 부터 트렌젝션이 시작됩니다.
그리고, Transaction 기본 전파 전략은 REQUIRED_NEW 이므로 이는, 기존 Transaction이 존재할 경우 새로 만들지 않습니다.
따라서 view에서 Service 메서드를 호출할 때 기존 트렌젝션을 사용하고, 해당 트렌젝션에서 사용하는 DataSource는 우리가 설정한 defaultDataSource를 사용하는데, 이 default dataSource가 readDatabase를 사용하게 되어서 Write시 writerDatabase를 사용할 수없는 문제가 발생하게 되었습니다.

다음에 그림으로 설명해 줄게용

2024-10-07 04:57 UTC, helenason approved these changes
수고했어용

2024-10-07 04:58 UTC, merged