feat: 총대마켓 접근권한 수정
woowacourse-teams/2024-chongdae-market pull request #514
Opened 2024-10-02 07:56 UTC by fromitive

## 📌 관련 이슈
close #507 
## ✨ 작업 내용
- 총대마켓 앱을 홍보하기 위해 웹에서 사용할 API를 추가했습니다.
- ⚠️ **해당 API는 쿠키 없이 접근 가능합니다.**
- 기존에 제공하는 API의 접근 권한을 수정하는 것 보다 `/read-only`로 시작하는 API end-point를 만들어서 관리하는 것이 편하다고 생각하여 이 구조를 사용하게 되었습니다.
## 📚 기타

혹시 이 설계에 의견 있으면 가감 없이 많은 의견 제시 부탁드립니다 (제발~~)

2024-10-04 02:32 UTC, helenason requested changes
기존 API 수정보다, API를 추가하는 방향을 택한 포케의 결정에 찬성합니다! 기존 생각했던 방향보다 구현 범위와 변경사항이 확 줄었네요. 앱과 웹 컨트롤러 분리도 가능하구요! 좋은데요?

다만, OfferingReadOnlyController 클래스명에 웹이 대상임을 명시하 건 어떨까요? (예를 들어 OfferingWebController?) 시간이 지나 이 컨트롤러를 보았을 때 어떤 목적으로 만들어진 컨트롤러지? 하는 의문이 생길 것 같아요.

저의 개인적인 의견이니 다른 분들의 의견도 궁금합니다~

수고하셨어요 :)

2024-10-06 17:17 UTC, masonkimseoul requested changes
좋은 구현 방안인 것 같습니다.
에버가 제시한 것처럼 Controller의 이름에서 외부용(web)인 것이 잘 드러나면 더 좋을 것 같아요.
고생하셨습니다!

2024-10-07 05:13 UTC, masonkimseoul approved these changes
web이란 표현이 더 모호해 질 수 있음(write 하는 메서드가 생길 수 있는 여지를 줄 수도..) 현행 유지하는게 어떤지?

2024-10-07 05:13 UTC, helenason approved these changes
수고하셨습니다~

2024-10-07 05:32 UTC, merged