refactor: 닉네임 생성 명사 파일 변경
woowacourse-teams/2024-chongdae-market pull request #518
Opened 2024-10-04 02:14 UTC by helenason

## 📌 관련 이슈
close #515 
## ✨ 작업 내용
- 닉네임 생성 명사 파일 변경: 팀원 이름 -> 랜덤 명사
- nouns.txt <-> nouns2.txt 파일명만 교체하였습니다.

## 📚 기타

2024-10-04 02:17 UTC, fromitive reviewed
에버 닉네임 잘 봤어요 

코멘트 남겼습니다~

2024-10-04 02:17 UTC, fromitive commented on backend/src/main/resources/static/nickname/nouns.txt
> +해,달,강,산,나무,바람,구름,별,불,물,꽃,새,호랑이,용,사자,고래,독수리,늑대,여우,곰,사슴,토끼,부엉이,까마귀,참새,매,황소,말,개,고양이,돼지,소,양,닭,거북이,두더지,원숭이,고릴라,코끼리,코뿔소,하마,바다,강아지,올빼미,두루미,까치,앵무새,나비,벌,개미,거미,나무늘보,고슴도치,오소리,공룡,피라미,상어,연어,새우,가재,붕어,잉어,돌고래,참치,연꽃,
`도라,포케,에버,메이슨,서기,알송,채채,제이슨,제임스,토미,포비,리사,총알` 도 넣으면 좋을텐데 ㅜㅜ 개발자로서 아쉽

2024-10-04 02:20 UTC, helenason commented on backend/src/main/resources/static/nickname/nouns.txt
> +해,달,강,산,나무,바람,구름,별,불,물,꽃,새,호랑이,용,사자,고래,독수리,늑대,여우,곰,사슴,토끼,부엉이,까마귀,참새,매,황소,말,개,고양이,돼지,소,양,닭,거북이,두더지,원숭이,고릴라,코끼리,코뿔소,하마,바다,강아지,올빼미,두루미,까치,앵무새,나비,벌,개미,거미,나무늘보,고슴도치,오소리,공룡,피라미,상어,연어,새우,가재,붕어,잉어,돌고래,참치,연꽃,
저도 제 이름 들어가게 하고 싶은데.... 사실 우테코 사용자 입장에선 에버라고 불리는 게 찝찝할 수도 ㅋㅋㅋㅋ

2024-10-04 02:41 UTC, fromitive commented on backend/src/main/resources/static/nickname/nouns.txt
> +해,달,강,산,나무,바람,구름,별,불,물,꽃,새,호랑이,용,사자,고래,독수리,늑대,여우,곰,사슴,토끼,부엉이,까마귀,참새,매,황소,말,개,고양이,돼지,소,양,닭,거북이,두더지,원숭이,고릴라,코끼리,코뿔소,하마,바다,강아지,올빼미,두루미,까치,앵무새,나비,벌,개미,거미,나무늘보,고슴도치,오소리,공룡,피라미,상어,연어,새우,가재,붕어,잉어,돌고래,참치,연꽃,
닉네임 리스트를 보다가 사소한 의견 하나 남길게용

제가 총대마켓을 가입했어요. 그런데? 제 닉네임이 `어쩌구 질뻐기` 혹은 `어쩌구 굴단`이 되면... 앱을 쓰지도 않고 나갈거같아요

긍정적인 이미지를 떠올릴 수 있는 명사를 넣는건 어떠실지 의견 드려요~

2024-10-06 17:21 UTC, masonkimseoul commented on backend/src/main/resources/static/nickname/nouns.txt
> +해,달,강,산,나무,바람,구름,별,불,물,꽃,새,호랑이,용,사자,고래,독수리,늑대,여우,곰,사슴,토끼,부엉이,까마귀,참새,매,황소,말,개,고양이,돼지,소,양,닭,거북이,두더지,원숭이,고릴라,코끼리,코뿔소,하마,바다,강아지,올빼미,두루미,까치,앵무새,나비,벌,개미,거미,나무늘보,고슴도치,오소리,공룡,피라미,상어,연어,새우,가재,붕어,잉어,돌고래,참치,연꽃,
ㅋㅋㅋ 그러고보니 각종 게임, 영화 등에서 나오는 이름들이 많이 보이네요. 무난하게 동식물 이름으로 바꿔볼까요,, 내일 준비해서 가보겠습니다..

2024-10-06 17:22 UTC, masonkimseoul requested changes
고생하셨습니다.
포케 코멘트에 이어서 달았아요!

2024-10-07 06:10 UTC, masonkimseoul approved these changes
고생요

2024-10-07 06:10 UTC, fromitive approved these changes
고생많았어요 에버~~~

2024-10-07 06:10 UTC, merged