refactor: OfferingRepository 쿼리 최적화
woowacourse-teams/2024-chongdae-market pull request #578
Opened 2024-10-12 16:07 UTC by helenason

## 📌 관련 이슈
close #540 

## ✨ 작업 내용
이번 작업 중 변경된 사안이 많은 편이라 관련하여 정리해둡니다.

### 🗂️ 쿼리 최적화 및 인덱스 설정 관련
노션 링크 첨부합니다.
https://silent-apparatus-578.notion.site/Offering-dddae682105e4c35b8aa157dba1d338b?pvs=4

### ♻️ 도메인 코드 리팩터링
기존 전략 패턴을 유지하면서 코드의 가독성을 높이기 위해 코드를 일부 수정했습니다.

#### 1️⃣ outOfRangeId() 접근 제어자 변경

OfferingFetchStrategy의 모든 자식 클래스에서 호출하는 로직이므로 중복이라 판단
-> fetchWithoutLast의 파라미터로 전달하도록 코드 수정
-> 외부 호출이 불필요해져 접근 제어자 변경 (protected -> private)

**AS-IS**
protected findOutOfRangeId()

**TO-BE**
private outOfRangeId()

#### 2️⃣ OfferingFetchStrategy 메서드명 축약

OfferingRepository의 메서드가 전체적으로 많은 파라미터를 받고 있기 때문에 개행이 많아져 가독성 저하
-> 해당 메서드를 사용하는 OfferingFetchStrategy 메서드명의 불필요한 어구를 줄임으로써 가독성 향상

**AS-IS**
fetchOfferings
fetchOfferingsWithoutLastId
fetchOfferingsWithLastOffering

**TO-BE**
fetch
fetchWithoutLast
fetchWithLast

#### 3️⃣ List<Offering> 합치는 메서드 생성

**AS-IS**
한방쿼리 사용하였으므로 존재하지 않았던 메서드

**TO-BE**
쿼리 최적화를 목적으로 쿼리 분리
-> 조회 쿼리의 결과인 List<Offering> 타입의 데이터 합치는 로직 필요
-> 아래 메서드를 OfferingFetchStrategy에 선언하여 자식 클래스에서 사용
```java
protected List<OfferingEntity> concatOfferings(Pageable pageable,
                                               Comparator<OfferingEntity> sortCondition,
                                               List<OfferingEntity>... offerings) {
    return Stream.of(offerings)
            .flatMap(Collection::stream)
            .sorted(sortCondition)
            .limit(pageable.getPageSize())
            .toList();
}
```

## 📚 기타
### git merge develop
깃 브랜치 전략이 변경됨에 따라, 아래 명령어를 통해 머지 후 PR 생성하였습니다.
```
git rebase develop
git checkout feature/~~~
git merge develop
```

2024-10-13 20:20 UTC, masonkimseoul requested changes
에버 고생하셨습니다!
수정하신 코드의 양이 꽤 되는데 진짜 고생했어요.
쿼리는 전보다 더 날라 갈 수 있겠지만 많이 깔끔해진 것 같아 오히려 좋은 것 같아요. 커넥션만 잘 조절하면 될 것 같습니다.
간단한 코멘트 남겨보았어요. 확인 부탁드립니다.

추가로 동적 쿼리의 필요성도 말씀해주셨는데, 쿼리 개수를 줄일 수 있을 것 같아서 사용하면 좋을 것 같습니다. QueryDsl 쓰면 좋을 것 같은데,,, 한 번 디깅해보고 사용해보죠.

검색어도 지금은 `:keyword%`으로만 사용하고 있으니, 전문 검색 인덱스도 달아보고 싶네요 ㅋㅋㅋ 가능할 진 모르겠지만.. 그 부분은 제가 해보겠습니다.

2024-10-13 20:20 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/RecentOfferingStrategy.java
> +    private List<OfferingEntity> of(List<OfferingEntity> firstOffering, List<OfferingEntity> secondOffering) {
메서드명을 `of`로 설정하신 이유가 있을까요? toXXX 와 같은 네이밍 말고 of로 선택하신 이유가 궁금합니다!

2024-10-13 20:20 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/RecentOfferingStrategy.java
> +        result.addAll(secondOffering);
제목으로 검색한 결과를 먼저 넣고, 주소로 검색한 결과를 다음으로 넣고 있네요. 정렬은 필요하지 않을까요?(단순 궁금)

2024-10-13 20:20 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/RecentOfferingStrategy.java
> +            return offeringRepository.findRecentOfferingsWithoutKeyword(lastOffering.getId(), pageable);
👍

2024-10-13 20:20 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/HighDiscountOfferingStrategy.java
> +                        pageable));
오~ sorting이 있었군요 👍

2024-10-13 20:20 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/ImminentOfferingStrategy.java
> +                .thenComparing(OfferingEntity::getId, Comparator.reverseOrder());
Comparator는 다른 클래스로 분리하면 어떨까요? 이 메서드가 과한 책임을 갖고 있다고 생각합니다.

2024-10-13 20:20 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/HighDiscountOfferingStrategy.java
> +                .thenComparing(OfferingEntity::getId, Comparator.reverseOrder());
이 부분도요! 다른 객체로 분리하면 어떨까요?

2024-10-13 23:14 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> 이유
> 
> 한방 쿼리를 여러 개의 쿼리로 분리함으로써 쿼리의 조건절 중복 발생
> 검색어의 유무에 따라 특정 조건절(o.title LIKE :keyword% OR o.meetingAddress LIKE :keyword%)의 존재 여부가 결정됨
> 라이브러리 종류
> 
> QueryDSL 혹은 JOOQ 도입 고려

동적쿼리 구성하는 데에 매우 찬성입니다. 다만, JPA에서 동적 쿼리를 작성할 때는 JPA Specification이라는 옵션도 고려해볼 수 있습니다. QueryDSL이나 JOOQ 같은 라이브러리를 도입하려는 이유가 동적 쿼리 작성 외에 다른 추가적인 장점이 있는지 고민해보면 좋겠습니다:)

2024-10-14 09:19 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/RecentOfferingStrategy.java
> +    private List<OfferingEntity> of(List<OfferingEntity> firstOffering, List<OfferingEntity> secondOffering) {
위 메서드는 여러개의 리스트를 합치는 메서드인데요!
구구가 학습테스트 코드에 사용하신 걸 보고 간결하고 가독성 또한 좋다고 생각해서 따라 사용해봤습니다 ㅎㅎ

2024-10-14 09:24 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/RecentOfferingStrategy.java
> +        result.addAll(secondOffering);
**커밋 내역을 보고 달아주신 리뷰 같은데요! 위 코드 역시 현재 존재하지 않고, concat 메서드에서 정렬을 진행하고 있어요!**

2024-10-14 09:26 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/ImminentOfferingStrategy.java
> +                .thenComparing(OfferingEntity::getId, Comparator.reverseOrder());
넵! 메서드 추출해보았습니다

[refactor: sortCondition 생성 메서드 추출](https://github.com/woowacourse-teams/2024-chongdae-market/pull/578/commits/edf54ae3dca5ee0f04239b636c3c4562208c7068)

2024-10-14 12:07 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
https://www.inflearn.com/community/questions/16685/specification-%EB%8C%80%EB%B9%84-querydsl%EC%9D%98-%EC%9E%A5%EC%A0%90%EC%9D%B4-%EC%96%B4%EB%96%A4%EA%B2%83%EC%9D%B4-%EC%9E%88%EC%9D%84%EA%B9%8C%EC%9A%94?srsltid=AfmBOorXE60T7wAFWEj2jeVzq3512PGYN4y3705De_30PhG_aIBP0PMf

<img width="782" alt="image" src="https://github.com/user-attachments/assets/0ace4a8b-4fe3-4d07-831e-b8f8d375bb94">

다음과 같은 의견들이 있는데, 도라가 제시해준 JPA Specification 옵션 또한 고려하여 다시 한번 도구 선택 고민해볼게요!

2024-10-16 01:39 UTC, masonkimseoul approved these changes
고생하셨습니다. minor한 코멘트 하나 남겼습니다. 크게 중요하지 않으니 나중에 진행하셔도 좋을 것 같아요!

2024-10-16 01:39 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/HighDiscountOfferingStrategy.java
> +    private Comparator<OfferingEntity> sortCondition() {
이 부분이 다른 클래스와 중복되어서 구현되어 있네요. 지금은 큰 문제 없지만, 나중에 Comparator용 클래스를 새로 파서 추상화하면 좋을 것 같습니다.

2024-10-16 01:39 UTC, merged