feat: FCM을 통해 푸쉬 알림 구현
woowacourse-teams/2024-chongdae-market pull request #605
Opened 2024-10-18 13:08 UTC by helenason

## 📌 관련 이슈
close #587 
## ✨ 작업 내용
- 문서화 작업 진행 중입니다.
## 📚 기타

2024-10-22 11:47 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/auth/service/dto/KakaoLoginRequest.java
> +                                @NotEmpty
회의 때 Nullable에서 NotEmpty로 바뀐 배경이 궁금했어요 😄 

이전 버전을 사용하는 사용자들이 fcmToken을 전달하지 않으면 어떻게 되나요? 
전달하지 않으면 fcmtoken 값은 어떻게 처리되나요? 

기존에 fcmtoken을 전달하지 않은 사용자들은 어떻게 처리되나요?  `checkFcmToken`으로 이미 값이 없으니 갱신하는 로직이 생략되는 걸까요~

2024-10-22 11:51 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/notification/exception/NotificationErrorCode.java
> +    INVALID_COMMENT_ROOM_STATUS(HttpStatus.INTERNAL_SERVER_ERROR, "존재하지 않는 거래 상태입니다."),
존재하지 않은 거래 상태가 나왔나요??

2024-10-22 11:57 UTC, fromitive commented on backend/src/main/resources/application-dev.yml
> +    path: /fcm/chongdaemarket-fcm-key.json
application.yml 파일에 이미 정의되어 있어서, 재정의 안해도 상관 없지 않나요?

2024-10-22 12:00 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/notification/domain/FcmTopic.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
정적팩터리 메서드를 사용하려고 설정하셨을까요? 😄

2024-10-22 12:04 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSubscriber.java
> +            e.printStackTrace();
notification이 제대로 구독되었는지 테스트하기 위해 남긴 로그 같아보여요
실패할 때만 어떤 사용자인지만 로깅하는건 어떨까요?

2024-10-22 12:04 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSubscriber.java
> +            e.printStackTrace();
이부분도 마찬가지에요~~

2024-10-22 12:06 UTC, fromitive approved these changes
에버 fcm하느라 정말 고생 많았어요..! 👍 

코드도 어떤 상황에서 Notification을 보내는지 잘 나뉘어져 있어서 읽기가 너무 편했어요 😄 

개인적으로 궁금한 부분들이 있어 코멘트 남깁니다~ 코멘트를 달아주셔도 되고 개인적으로 가볍게 알려줘도 되요~ approve 드려요~

2024-10-22 12:55 UTC, masonkimseoul requested changes
안녕하세요 에버!
코드 엄청 많이 작성해주셨네요. 짧은 기간동안 잘 구현하시느라 고생 많았어요.
오늘 설명 잘 해주셔서 코드 이해하는데 큰 어려움 없었습니다.
객체도 전반적으로 잘 분리해주셨네요.
그런데 지금 로그가 많이 찍히는 것 같아요. 실패한 상황 위주로만 남겨두면 좋을 것 같습니다.
감사합니다.

2024-10-22 12:55 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/notification/service/message/FcmMessageCreator.java
> +    private static FcmMessageCreator INSTANCE;
싱글턴 👍

2024-10-22 12:55 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
> +            log.info("토큰 갱신 사용자 id: {}", member.getId());
이 로그는 빼는게 어떨까요?

2024-10-22 12:55 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/notification/domain/FcmData.java
> +        data.forEach((key, value) -> log.info("{} : {}", key, value));
이 로그도 빼는 건 어떨까요?

2024-10-23 01:58 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
> +    private void checkFcmToken(MemberEntity member, String fcmToken) {
fcmToken이 null일 때 처리 추가합시다!

2024-10-23 01:58 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
> +        return login(member, request.fcmToken());
fcmToken이 null일 때 처리 추가합시다~

2024-10-23 02:02 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/notification/domain/FcmTopic.java
> +    private static final String TOPIC_FORMAT_OFFERING_MEMBER = "member_of_offering_%d";
이 부분도 회의 때 논한대로 participant_of_offering_%d 로 변경합시다!

2024-10-23 04:08 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/notification/service/message/FcmMessageCreator.java
> +    public Message createMessage(FcmToken token, FcmData data) {
static 메서드로 쓰는 건 어떨까요?

2024-10-23 04:15 UTC, ChooSeoyeon commented on backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationService.java
>          return notificationSender.send(message);
순서가 아래처럼 되면 더 좋을 거 같습니다!
```
        FcmTopic topic = FcmTopic.offeringMemberTopic(offeringMember.getOffering());
        notificationSubscriber.subscribe(offeringMember.getMember(), topic);
        Message message = participationMessageManager.messageWhenParticipate(offeringMember);
        return notificationSender.send(message);
```
또한, notificationSender.send(message)의 성공값이 무엇인지 궁금합니다! FcmNotificationSerivice가 해당 값을 응답해야 하는 이유가 따로 있었나요??

2024-10-23 04:17 UTC, ChooSeoyeon commented on backend/src/test/java/com/zzang/chongdae/notification/service/FcmNotificationTest.java
이 테스트 클래스 이름을 FcmNotificationServiceTest로 하지 않고 FcmNotificationTest로 하신 이유가 따로 있었나요??

2024-10-23 05:33 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/auth/service/dto/KakaoLoginRequest.java
> +                                @NotEmpty
`checkFcmToken`을 통해 DB에 저장된 토큰과 요청된 토큰이 다를 경우 갱신합니다. 로그인의 토큰 갱신과 비슷한 개념이라고 생각하시면 돼요.

`@NotEmpty`로 설정한 이유는, fcm 서버에 알림을 send할 때 빈 값의 토큰에 대해 알림을 전송하지 않도록 하기 위함이었어요. 빈 문자열 토큰에 대해 알림을 전송하면 예외가 터져서요. 따라서 fcmToken은 클라이언트 측으로부터 비지 않은 상태로 들어와야 한다고 생각했습니다.

2024-10-23 05:35 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/notification/domain/FcmTopic.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
정확합니다!

2024-10-23 05:36 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSubscriber.java
> +            e.printStackTrace();
FCM 관련 내용은 로그를 통해서만 확인이 가능해요! 저희는 현재 DB에 저장하지 않고 있구요 ㅠㅠ 따라서 로그는 최대한 자세히 남기도록 하였습니당

2024-10-23 05:37 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
> +            log.info("토큰 갱신 사용자 id: {}", member.getId());
위에서 포케의 리뷰에 작성해둔 부분 참고해주세요 :-) 감사합니다

2024-10-23 05:51 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
> +        return login(member, request.fcmToken());
```java
if (fcmToken == null) {
    member.updateFcmToken("invalid_%d".formatted(member.getId()));
    return;
}
```
위 방식을 통해 현재 DB 내 default 값으로 설정되도록 하였습니다!

2024-10-23 05:53 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationService.java
>          return notificationSender.send(message);
첫번째 의견 반영하도록 하겠습니다!

추가로, `notificationSender.send(message)`의 성공값은 fcm서버가 설정한 messageId입니다. 테스트를 통해 알림 전송이 잘 되었는지 확인하고 싶어 응답값을 설정했어요.

2024-10-23 06:18 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/notification/service/message/FcmMessageCreator.java
> +    public Message createMessage(FcmToken token, FcmData data) {
협의 후 FcmMessageCreator를 빈으로 등록하도록 하였습니다!

2024-10-23 06:29 UTC, helenason commented on backend/src/test/java/com/zzang/chongdae/notification/service/FcmNotificationTest.java
따로 없습니다! 변경하겠습니다 :)

2024-10-23 06:42 UTC, helenason commented on backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationService.java
>          return notificationSender.send(message);
협의 후 Service에서는 messageId를 반환하지 않도록 변경하였습니다!

2024-10-23 06:44 UTC, ChooSeoyeon approved these changes
고생하셨어요!!!!

2024-10-23 06:45 UTC, masonkimseoul approved these changes
최고존엄 에버

2024-10-23 06:46 UTC, merged