refactor: 데이터베이스 락을 통해 중복 참여 방지
woowacourse-teams/2024-chongdae-market pull request #673
Opened 2024-12-19 11:52 UTC by helenason

## 📌 관련 이슈
close #664
## ✨ 작업 내용
### 목적
같은 사용자가 같은 공모에 중복 참여 가능한 상황을 해결하기 위함.

### 해결
동시성 이슈 해결 과정은 [제 블로그](https://helenason.tistory.com/21)에 정리해두었어요. 자세한 내용이 궁금하시면 읽어주시면 됩니다! 조회수 늘리기는 덤 ㅎㅎ

요약해서 이야기하자면, 총 네 가지 방법을 떠올렸고 그 중 두 가지 방법 낙관적 잠금과 비관적 쓰기 잠금을 적용할 수 있었어요. 저는 비관적 쓰기 잠금을 걸기로 결정했습니다.

먼저, 참여하기 API는 동시성 이슈 발생률이 낮은 편이기 때문에 속도 테스트를 해보았을 때 낙관적 잠금과 비관적 잠금의 차이가 없었어요. 그래서 성능 측면은 고려하지 않았고, 불필요하게 쿼리가 발생하는 낙관적 잠금의 단점을 피하기 위해 비관적 쓰기 잠금을 선택하도록 하였습니다! 블로그에는 언급하지 않았지만, 낙관적 잠금을 선택할 경우 적절한 예외 처리에 대한 고민이 길어지기도 했어요.
## 📚 기타

2024-12-22 00:23 UTC, fromitive requested changes
오우 에버 정말 고생많았어요! 

블로그도 가독성있게 잘 써서 동시성 이슈에 대해 이해하기 수월했어요!
또한, 동시성 테스트를 위한 테스트 코드도 많이 고민한 흔적이 느껴졌습니다 😄 

몇가지 의견 남겼으니 확인 부탁드립니다!

2024-12-22 00:23 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
> -    List<OfferingEntity> findCommentRoomsByMember(MemberEntity member);
불필요한 쿼리메서드 지워준것 확인 완료~~

2024-12-22 00:23 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
>      }
[refactor: 공모 상태 업데이트 로직 이동](https://github.com/woowacourse-teams/2024-chongdae-market/pull/673/commits/d6a018a4bf24e6c4a428fe46b26baebaf1528c29)
위의 커밋에 관한 내용이네요! 서비스 로직을 줄이는 효과를 얻게 되었어요

다른 방법으론 offeringService를 세부 서비스로 나누는 방식도 있겠는데요, 공모상태 업데이트 로직을 서비스 로직이 아닌 엔티티에 넣는 선택을 한 이유가 있으신가요?

2024-12-22 00:23 UTC, fromitive commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> -        OfferingEntity savedOffering = offeringRepository.save(offering);
오호 saved로 네이밍도 변경하셨군요 좋은데요?

2024-12-22 00:23 UTC, fromitive commented on backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java
> +            }
블로그에서 본 코드네요 
`try ... catch` 문으로 인해 인덴트가 늘어낫어요! 

가능하다면 해당 로직을 `ConcurrencyExecutor` 같은 네이밍의 객체로 옮겨보는건 어떻게 생각하세요?

2024-12-22 15:52 UTC, masonkimseoul approved these changes
고생하셨습니다 에버! 테스트 코드까지 잘 작성해주셨네요.

저는 이렇게 락을 거는 방식은 속도 때문에 지양해야 한다고 알고 있었는데, 블로그 글을 보고 이해할 수 있었어요. 진행했던 성능 테스트의 결과도 함께 알려주면 좋을 것 같아요~

2024-12-22 15:52 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
>      }
이 부분은 아직 도메인으로 이관되지 않은 서비스 로직이라 생각합니다! 외부에서 `offering.toOfferingJoinedCount().decideOfferingStatus()`와 같이 호출하는 형태가 아직 서비스에 남아있어요. 그러한 코드들을 앞으로 도메인으로 옮겨야 한다고 생각합니다.

2024-12-22 15:52 UTC, masonkimseoul commented on backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
> +        OfferingEntity saved = offeringRepository.save(offering);
어차피 이 서비스에서는 OfferingEntity만 저장될테니 saved로만 명명해도 괜찮을 것 같네요. 다른 무언가가 저장될 소요가 있다면 그 때 다시 바꾸면 좋겠습니다.

2024-12-23 09:11 UTC, helenason commented on backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java
> +            }
오! 너무 좋은 방향인데요? 현재 service 테스트 클래스와 integration 테스트 클래스 모두에서 사용되는 코드이기 때문에 global.helper 패키지에 ConcurrenyExecutor 클래스를 위치시켜 동시 실행 코드를 작성해볼게요!

2024-12-24 08:42 UTC, fromitive approved these changes
에버~ 동시성 테스트를 간편화하기 위해 객체로 묶은 점 인상적이었어요..! 

간단한 코멘트 하나 남겼으니 확인 부탁드려용

나머지 부분 이상이 없어서 Approve 할게요!

2024-12-24 08:42 UTC, fromitive commented on backend/src/test/java/com/zzang/chongdae/global/helper/ConcurrencyExecutor.java
> +        return INSTANCE;
에버의 의도가 궁금해서 물어봅니다!

싱글턴으로 만든이유는 스프링의 빈 생명주기와 다르기 때문일까요? 

이 객체를 사용하는 테스트를 지우지 않는 이상, ConcurrencyExecutor는 빈 생명주기와 같을 것이라고 예상이 되는데 제가 놓친 부분이 있다면 코맨트 부탁드립니다..!

2024-12-24 16:07 UTC, helenason commented on backend/src/test/java/com/zzang/chongdae/global/helper/ConcurrencyExecutor.java
> +        return INSTANCE;
테스트 코드를 작성할 때 하나의 메서드 안에서만 사용하고 싶었어요! 그래서 @Autowired가 아닌 new 생성자를 사용해 객체를 만들고 싶었고 빈 객체가 아닌 POJO 객체를 싱글톤으로 관리하도록 하였습니다. 혹시 더 좋은 방법이 있으면 알려주셔도 좋아요 :)

2024-12-24 16:13 UTC, merged